# -*- coding: utf-8 -*-
"""Pdf_Sharepoint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQ1vDRgBdRNYgc7_-4m20QfZnetfKv4s
"""

pip install msal requests

import os
import requests
from msal import PublicClientApplication

# ✅ FOR COLAB/JUPYTER: upload file interactively
from google.colab import files
uploaded = files.upload()  # This shows a file picker for user to upload a file

# ✅ Grab the uploaded file path
file_path = list(uploaded.keys())[0]
print(f"📄 You uploaded: {file_path}")

# === 🔐 Azure App Registration Details ===
client_id = "42d4bf53-30f7-4522-ba5e-83a5dff792d6"
tenant_id = "2b30530b-69b6-4457-b818-481cb53d42ae"
authority = f"https://login.microsoftonline.com/{tenant_id}"

# === Microsoft Graph Scopes ===
scopes = ["Files.ReadWrite.All", "Sites.ReadWrite.All"]

# === SharePoint Info ===
sharepoint_site_hostname = "luky.sharepoint.com"
site_path = "/sites/CS499-CofA"
sharepoint_folder = "Shared Documents/COFA_PDFs"

# === Authenticate with MSAL ===
app = PublicClientApplication(client_id=client_id, authority=authority)
result = None
accounts = app.get_accounts()
if accounts:
    result = app.acquire_token_silent(scopes=scopes, account=accounts[0])

if not result:
    flow = app.initiate_device_flow(scopes=scopes)
    if "user_code" not in flow:
        raise Exception("⚠️ Device flow initiation failed.")
    print(f"🔐 Go to: {flow['verification_uri']}")
    print(f"🔑 Enter the code: {flow['user_code']}")
    result = app.acquire_token_by_device_flow(flow)
    print("🔎 Token response:", result)

if "access_token" not in result:
    raise Exception(f"❌ Authentication failed.\nDetails: {result.get('error_description')}")

access_token = result["access_token"]
headers = {"Authorization": f"Bearer {access_token}"}

# === Get SharePoint Site ID and Drive ID ===
site_url = f"https://graph.microsoft.com/v1.0/sites/{sharepoint_site_hostname}:{site_path}"
site_id = requests.get(site_url, headers=headers).json()["id"]
drive_id = requests.get(f"https://graph.microsoft.com/v1.0/sites/{site_id}/drive", headers=headers).json()["id"]

# === Upload PDF ===
file_name = os.path.basename(file_path)
upload_url = f"https://graph.microsoft.com/v1.0/drives/{drive_id}/root:/{sharepoint_folder}/{file_name}:/content"

print(f"⏫ Uploading '{file_name}' to SharePoint folder '{sharepoint_folder}'...")

with open(file_path, "rb") as f:
    upload_resp = requests.put(upload_url, headers=headers, data=f)

if upload_resp.status_code in [200, 201]:
    print(f"✅ Success! '{file_name}' uploaded to SharePoint.")
else:
    print(f"❌ Upload failed: {upload_resp.status_code}")
    print(upload_resp.text)

