# -*- coding: utf-8 -*-
"""REG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROj7eD2bSy2CJI40B7ecSAPuaard7PNZ
"""

import re
from pathlib import Path

file_path = Path("/content/Raw Material_Evan.txt")

patterns = {
    'Product Name': r'Product Name\s*(.*)',
    'Batch Number': r'Batch Number\s*(\S+)',
    'Vehicle Number': r'Vehicle Number\s*(\S+)',
    'Production Date': r'Production Date\s*(\S+)',
    'Shelf life Exp Date': r'Shelf life Exp Date\s*(\S+)',
    'Quantity': r'Quantity\s*([\d,\.]+)',
    'Delivery No': r'Delivery No\s*(\S+)',
    'Customer Name': r'Ship to\s*([\w\s]+)',
    'Customer Address': r'Ship to\n(.*?)\n',
    'Ref No': r'Ref No\s*/\s*Cust PO\s*/\s*Date\s*(\S+)',
    'Signature': r'Signature\s*(.*)',
}

def extract_data(file_path, patterns):
    extracted_data = {}
    # Read the content of the file
    with open(file_path, 'r') as file:
        file_content = file.read()

    for key, pattern in patterns.items():
        match = re.search(pattern, file_content, re.DOTALL)  # DOTALL flag to allow multiline matching
        if match:
            extracted_data[key] = match.group(1).strip()
        else:
            extracted_data[key] = None
    return extracted_data

# Extract data
extracted_data = extract_data(file_path, patterns)

for key, value in extracted_data.items():
    print(f"{key}: {value}")

